### ISSUE TITLE
How to access installed programs (path)?

### ISSUE THREAD

**Issue by scivision** [Cyberboss/install-winget#2]
What path are executables installed to? On a local physical computer it's like

```
$env:LOCALAPPDATA/Microsoft/WinGet/Links/ffmpeg.exe
```

example:

```yml
    - name: install prereqs (Windows)
      if: runner.os == 'Windows'
      run: winget install ffmpeg --disable-interactivity --accept-source-agreements

    - name: FFMPEG version
      run: ffmpeg --version
```

ffmpeg.exe is not on PATH
